"""
Django settings for appflut project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!_=hia%yw+d$ics+^*2(v)i1$!-zk&gjy&kd0taq9zvy-hl!96'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webflut',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'appflut.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'appflut.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGIN_URL = 'home'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CSRF_TRUSTED_ORIGINS = [
    'https://65a6-178-127-32-71.ngrok-free.app',
    ' https://65a6-178-127-32-71.ngrok-free.app/register/',
    ' https://65a6-178-127-32-71.ngrok-free.app/person_info/',
    ' https://65a6-178-127-32-71.ngrok-free.app/login/',
    ' https://65a6-178-127-32-71.ngrok-free.app/logout/',
    ' https://65a6-178-127-32-71.ngrok-free.app/calories_and_bjy/',
    ' https://65a6-178-127-32-71.ngrok-free.app/profile/',
    ' https://65a6-178-127-32-71.ngrok-free.app/report/',
    ' https://65a6-178-127-32-71.ngrok-free.app/breakfast/',
    ' https://65a6-178-127-32-71.ngrok-free.app/lunch/',
    ' https://65a6-178-127-32-71.ngrok-free.app/dinner/',
    ' https://65a6-178-127-32-71.ngrok-free.app/snack/',
    ' https://65a6-178-127-32-71.ngrok-free.app/activities/',
    ' https://65a6-178-127-32-71.ngrok-free.app/eatingbase/',
    ' https://65a6-178-127-32-71.ngrok-free.app/add_breakfast/',
    ' https://65a6-178-127-32-71.ngrok-free.app/add_lunch/',
    ' https://65a6-178-127-32-71.ngrok-free.app/add_dinner/',
    ' https://65a6-178-127-32-71.ngrok-free.app/add_snack/',
    ' https://65a6-178-127-32-71.ngrok-free.app/add_activity_view/',
    ' https://65a6-178-127-32-71.ngrok-free.app/remove_from_list/<int:product_id>/',
    ' https://65a6-178-127-32-71.ngrok-free.app/remove_from_list2/<int:product_id>/',
    ' https://65a6-178-127-32-71.ngrok-free.app/delete_activity/<int:id>/',
    ' https://65a6-178-127-32-71.ngrok-free.app/edit_person_info/',
    ' https://65a6-178-127-32-71.ngrok-free.app/creategroup/',
    ' https://65a6-178-127-32-71.ngrok-free.app/groupdetail/<int:group_id>/',
    ' https://65a6-178-127-32-71.ngrok-free.app/adduser/<int:group_id>/',
    ' https://65a6-178-127-32-71.ngrok-free.app/removeuser/<int:group_id>/',
    ' https://65a6-178-127-32-71.ngrok-free.app/userinfo/<int:user_id>/',
    ' https://65a6-178-127-32-71.ngrok-free.app/step1/',
    ' https://65a6-178-127-32-71.ngrok-free.app/step2/',
    ' https://65a6-178-127-32-71.ngrok-free.app/step3/',
    ' https://65a6-178-127-32-71.ngrok-free.app/step4/',
    ' https://65a6-178-127-32-71.ngrok-free.app/step5/',
    ' https://65a6-178-127-32-71.ngrok-free.app/display_chart/',

    # Другие доверенные источники (если есть)
]


PWA_APP_NAME = 'Калькулятор калорий'
PWA_APP_DESCRIPTION = "My app description"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait-primary'
PWA_APP_START_URL = 'https://65a6-178-127-32-71.ngrok-free.app'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/icons/1616.png',
        'sizes': '160x160'
    },
    {
        "src": "/static/icons/aurss.96x96.png",
        "sizes": "96x96",
        "type": "image/png"
    },
    {
        "src": "/static/icons/152.png",
        "sizes": "152x152",
        "type": "image/png"
    },

    {
        "src": "/static/icons/192.png",
        "sizes": "192x192",
        "type": "image/png"
    },
    {
        "src": "/static/icons/384.png",
        "sizes": "384x384",
        "type": "image/png"
    },

    {
        "src": "/static/icons/aurss.512x512.png",
        "sizes": "512x512",
        "type": "image/png"
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/icons/1616.png',
        'sizes': '160x160'
    },
    {
        "src": "/static/icons/aurss.512x512.png",
        "sizes": "512x512",
        "type": "image/png"
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/icons/6411.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_APP_SHORTCUTS = [
    {
        'name': 'Shortcut',
        'url': '/target',
        'description': 'Shortcut to a page in my application'
    }
]
PWA_APP_SCREENSHOTS = [
    {
      'src': '/static/icons/7513.png',
      'sizes': '750x1334',
      "type": "image/png",
        "form_factor": "wide",
        "label": "Wonder Widgets"

    },
    {
        'src': '/static/icons/1072.png',
        'sizes': '1080x1920',
        "type": "image/png",
        "label": "Wonder Widgets"

    }
]


PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'serviceworker.js')

# PWA_SERVICE_WORKER_PATH = 'static/serviceworker.js'