# Generated by Django 4.2.4 on 2023-10-15 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webflut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('calories_in', models.TextField()),
                ('proteins', models.TextField()),
                ('fats', models.TextField()),
                ('carbohydrates', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
