# Generated by Django 4.2.4 on 2023-10-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0002_add_product_alter_personal_inform_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webflut.add_product')),
            ],
        ),
    ]
