# Generated by Django 4.2.4 on 2023-10-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0004_alter_add_product_calories_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='calories_in',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='carbohydrates',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='fats',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='proteins',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='height',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='weight',
            field=models.TextField(),
        ),
    ]
