# Generated by Django 4.2.4 on 2023-10-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0005_alter_add_product_calories_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webflut.add_product')),
            ],
        ),
        migrations.CreateModel(
            name='Lunch_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webflut.add_product')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webflut.add_product')),
            ],
        ),
    ]
