# Generated by Django 4.2.4 on 2023-10-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0007_activities_activities_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities_add',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
