# Generated by Django 4.2.4 on 2023-10-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0008_activities_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
            ],
        ),
    ]
