# Generated by Django 4.2.4 on 2023-10-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0009_time_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ttime_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Time_Test',
        ),
    ]
