# Generated by Django 4.2.4 on 2023-10-18 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0011_activities_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast_products',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dinner_products',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lunch_products',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='snack_products',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
