# Generated by Django 4.2.4 on 2023-10-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0013_breakfast_products_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_products',
            name='weight',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='lunch_products',
            name='weight',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='snack_products',
            name='weight',
            field=models.TextField(default=0),
        ),
    ]
