# Generated by Django 4.2.4 on 2023-10-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0014_dinner_products_weight_lunch_products_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=200)),
                ('met', models.FloatField()),
            ],
        ),
    ]
