# Generated by Django 4.2.4 on 2023-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0019_alter_activities_add_product_delete_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_inform',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
