# Generated by Django 4.2.4 on 2023-10-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0020_alter_personal_inform_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_inform',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
