# Generated by Django 4.2.4 on 2023-10-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0021_alter_personal_inform_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='calories_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='carbohydrates',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='fats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='proteins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='breakfast_products',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dinner_products',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lunch_products',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snack_products',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
