# Generated by Django 4.2.4 on 2023-10-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0023_alter_activity_options_alter_add_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='calories_in',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='carbohydrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='proteins',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breakfast_products',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dinner_products',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lunch_products',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='snack_products',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
