# Generated by Django 4.2.4 on 2023-10-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0024_alter_add_product_calories_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_inform',
            name='date_of_birth',
            field=models.FloatField(),
        ),
    ]
