# Generated by Django 4.2.4 on 2023-10-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0025_alter_personal_inform_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_inform',
            name='goals',
            field=models.CharField(choices=[('L', 'Похудение'), ('M', 'Набор массы'), ('F', 'Поддержание веса')], max_length=1),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1),
        ),
    ]
