# Generated by Django 4.2.4 on 2023-10-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0033_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_inform',
            name='first_name',
            field=models.CharField(default='test1', max_length=10),
        ),
        migrations.AddField(
            model_name='personal_inform',
            name='last_name',
            field=models.CharField(default='test2', max_length=10),
        ),
    ]
