# Generated by Django 4.2.4 on 2023-10-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0035_alter_personal_inform_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_inform',
            name='date_of_birth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='weight',
            field=models.FloatField(),
        ),
    ]
