# Generated by Django 4.2.4 on 2023-10-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0036_alter_personal_inform_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_inform',
            name='height',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='personal_inform',
            name='weight',
            field=models.FloatField(default='0'),
        ),
    ]
