# Generated by Django 4.2.4 on 2023-10-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0041_alter_personal_inform_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_inform',
            name='date_of_birth',
            field=models.FloatField(default=0),
        ),
    ]
