# Generated by Django 4.2.4 on 2023-11-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0043_step1model_step2model_step3model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(choices=[('L', 'Похудение'), ('M', 'Набор массы'), ('F', 'Поддержание веса')], default='L', max_length=1)),
                ('active', models.CharField(choices=[('L', 'Низкая активность'), ('M', 'Средняя активность'), ('H', 'Высокая активность')], default='L', max_length=1)),
            ],
        ),
    ]
