# Generated by Django 4.2.4 on 2023-11-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0044_step4model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_male', models.BooleanField(verbose_name='Мужчина')),
                ('is_female', models.BooleanField(verbose_name='Женщина')),
            ],
        ),
    ]
