# Generated by Django 4.2.4 on 2023-11-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0046_step5model_remove_step4model_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_inform',
            name='active',
            field=models.CharField(choices=[('L', 'малоактивный'), ('M', 'активный')], default='L', max_length=1),
        ),
    ]
