# Generated by Django 4.2.4 on 2023-11-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0047_alter_personal_inform_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2model',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('', '')], default='', max_length=1),
        ),
    ]
