# Generated by Django 4.2.4 on 2023-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0049_delete_step2model_alter_personal_inform_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step3model',
            name='height',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='step3model',
            name='weight',
            field=models.IntegerField(default='0'),
        ),
    ]
