# Generated by Django 4.2.4 on 2023-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0050_alter_step3model_height_alter_step3model_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step3model',
            name='height',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='step3model',
            name='weight',
            field=models.IntegerField(default=''),
        ),
    ]
