# Generated by Django 4.2.7 on 2023-12-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0051_alter_step3model_height_alter_step3model_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast_products',
            name='calories_in',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='breakfast_products',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='breakfast_products',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='breakfast_products',
            name='proteins',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
