# Generated by Django 4.2.6 on 2023-12-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0054_dinner_products_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
