# Generated by Django 4.2.6 on 2023-12-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0055_water'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Water',
        ),
    ]
