# Generated by Django 4.2.6 on 2023-12-07 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0057_waterconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterconsumption',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
