# Generated by Django 4.2.6 on 2023-12-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0059_alter_personal_inform_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='calories_in',
            field=models.FloatField(default=0),
        ),
    ]
