# Generated by Django 4.2.6 on 2024-04-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0061_group_creator_alter_group_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_for_children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=200)),
                ('met', models.FloatField()),
            ],
            options={
                'verbose_name': 'Виды Детских Активностей ',
                'verbose_name_plural': 'Виды Детских Активностей',
            },
        ),
    ]
