# Generated by Django 4.2.6 on 2024-04-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webflut', '0062_activity_for_children'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity_for_children',
        ),
    ]
